---
title: "ReadMe"
author: "Devansh Saxena"
date: "July 14, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Basic Overview

This project is based off the book written by Michael Lewis 
(later turned into a movie).

By doing Exploratory Data analysis on Batting.csv and Salaries.csv
we predicted the Best Under valued Replacement players for Oakland
A as they lost there 3 key players in the starting of the season.

Did these analysis using R.

I am using data from Sean Lahaman's Website a very useful source for 
baseball statistics. 

## Baseball Abbreviations used in this project

AB: At bats
BA: Batting average
BB: Base on balls (walk)
BF: Batters faced
CS: Caught stealing
FO: Foul out
H : Hits
HBP: Hit by pitch
HR: Home Run
IBB: Intentional base on balls
MLB: Major League Baseball
OBP: On base percentage
R: Run scored
RBI: Run batted in
SB: Stolen base
SF: Sacrifice Fly
SLP: Slugging percentage
TB: Total bases
X1B : Singles
X2B : Doubles
X3B : Triples
XBH : Extra Base Hits
